### ISSUE TITLE
create-instance should detect un-recoverable errors

### ISSUE THREAD

**Issue by akariv** [ViderumGlobal/ckan-cloud-docker#12]
When cca-operator create-instance / update-instance fails to start an instance (e.g. bad configuration causing ckan or its dependencies to crashloop), it should exit with a proper exit code and not wait indefinitely.

**Comment by OriHoch** [comment]
latest deployed version have a timeout of 10 minutes for waiting for instance status (after each deployment - first for creation and 2nd for full deployment)
