### ISSUE TITLE
Create self-hosted installation guide

### ISSUE THREAD

**Issue by akariv** [ViderumGlobal/ckan-cloud-docker#28]
We want to install CKAN in a self-hosted environment.
Usually this means clients owning a machine (or machines), but not k8s cluster.

We need to create an internal installation guide for this scenario, using what we have (i.e. not plain vanilla ckan) - e.g. using our docker compose setup.

Write a document containing:
- [ ] Prerequisites
  - [ ] what HW is needed - based on expected usage / amount of data
  - [ ] which services are needed (e.g. database, storage) - based on cloud provider (if any) 
- [ ] Checklist - things to check on the system before starting
- [ ] Installation guide - step by step list of tasks to set up a working ckan instance based on existing, custom images 
- [ ] Peripherals
  - [ ] Setting up backup with common cloud providers
  - [ ] Setting up external domain + SSL
  - [ ] Error reporting
  - [ ] Availability
  - [ ] Monitoring (with common cloud providers)

/cc @OriHoch to review

**Comment by OriHoch** [comment]
what about installing a light-weight Kubernetes and running ckan-cloud over it?

https://microk8s.io/ is built for this use-case

**Comment by OriHoch** [comment]
would be good to understand the reasons for doing that and the requirements these clients have regarding these self-hosted setups

**Comment by akariv** [comment]
microk8s would be a suitable solution - we need to find something that would work on most client environments. Naturally, we would have to provide a support and manual document to go with our software, so the least we have to add to the plain vanilla CKAN user guide the better.

(re reasons: they vary - IT manager requirement, budget, existing hw etc - but the fact is that not all clients want to pay us for hosting.)

**Comment by akariv** [comment]
requirements also vary, so our solution should focus on flexibility and as few as possible external dependencies.

**Comment by OriHoch** [comment]
from what I see, microk8s is very compatible with various platforms

if the main consideration is not paying for hosting, but still wanting our support and centralized management, worth to go with the k8s way, that way we can also do centralized management of this infra. as part of our regular cloud

we could also provide some optional non-critical / non-sensitive centralized services like logging / monitoring / debug / centralized datapusher / solr etc.

**Comment by OriHoch** [comment]
we could offer a hybrid cloud solution where the CKAN instance and minio storage is self-hosted but other components can be external / based on current supported services like gcloud SQL / amazon RDS / SearchStax solrcloud etc..

**Comment by OriHoch** [comment]
dumping some more ideas.. 

We could offer different service options, e.g.:

* basic self-hosted - simple environment based on docker-compose all on a single machine
* advanced self-hosted - for more advanced requirements / scale - self-host on Kubernetes using ckan-cloud-operator
* hybrid hostring - provide us with a kubeconfig file for  your clsuter, setup to our specifications and we will deploy and manage everything for you on your cluster

**Comment by akariv** [comment]
I would say that the main reason is not money related at all - but more to security, privacy, hosting sensitive data outside of national borders etc.

The basic assumption here is that we won't be doing the maintenance - just the installation. - and local admins who will do the day to day maintenance.

Therefore it would be easier for us to choose a single preferred options that's easy to deploy and maintain and go with it.
