### ISSUE TITLE
create_instance tries to add collection on evicted solr pod

### ISSUE THREAD

**Issue by akariv** [ViderumGlobal/ckan-cloud-docker#30]
When trying to add new instance, there were a few evicted solrcloud pods in the cluster.
create_instance doesn't check for the pod's status, and tries to create the collection using a command on an evicted pod and not the actually running one.

**Comment by OriHoch** [comment]
@akariv deployed + tested, infrastructure seems fine but seems there are some bugs with the CKAN app: #32
