### ISSUE TITLE
docker-compose dev environment - support okfn docker stack, improve dev flows

### ISSUE THREAD

**Issue by OriHoch** [ViderumGlobal/ckan-cloud-docker#33]
There are a few standard CKAN docker setups used for development in different projects, we would like to converge on a common base CKAN docker setup which will allow to get updates and patches developed faster and deployed more reliably. 

Following are the main setups:

* https://github.com/ViderumGlobal/ckan-cloud-docker
* https://github.com/okfn/docker-ckan
* https://github.com/CivicActions/ckanext-ed/blob/master/Makefile / https://github.com/CivicActions/ckanext-ed/blob/master/README.md

Some example of questions the dev docs should address:

* How do I quickly install CKAN and have a running instance locally with docker? (I think already solved)
* How do I create an extension template in my local machine using paster commands knowing that CKAN is in the dockerized env?
* How do I separate that extension in a new git repo so I can have independence to install it in other instances?
* How do I quickly refresh the changes in my extension into the dockerized env so I can have quick feedback of my changes?
* How do I run the tests for my extension in the dockerized env so I can have a quick test-development cycle?
* How do I debug my methods in the dockerized env so I can have a better understanding of whats going on with my logic?

related: datopian/ckan.io#90

**Comment by starsinmypockets** [comment]
Following. As a new ckan dev I lost a fair bit of time finding a suitable template for extension development with docker-compose. I ended up using https://github.com/okfn/docker-ckan which includes _most_ of the points listed above in your initial comment and could probably serve as a template for an "Extension Development" section in the README?
