### ISSUE TITLE
Error loading datagov-tjheme

### ISSUE THREAD

**Issue by avdata99** [ViderumGlobal/ckan-cloud-docker#70]
Runnig the _datagov-theme_ configuration (without the NG harvester yaml file)
```
docker-compose -f docker-compose.yaml \
    -f .docker-compose-db.yaml   \
    -f .docker-compose.datagov-theme.yaml \
    up
```

fails to load Nginx
```
2019/12/31 17:07:22 [emerg] 1#1: host not found in upstream "harvester" in /etc/nginx/conf.d/default.conf:9
nginx_1                | nginx: [emerg] host not found in upstream "harvester" in /etc/nginx/conf.d/default.conf:9

```

ckan:5000 works fine

Task:

 - [ ] Allow Datagov to work without NG Harvester

Analysis:
Best solution is to extend the nginx config in NG Harvster yaml file. If this is not possible we need top ensure nginx to ignore this error.

**Comment by akariv** [comment]
Just to note that this issue is for the development environment only - in
production we already have a solution for this.
